### ISSUE TITLE
建议增加几张界面示意图

### ISSUE THREAD

**Issue by xtyDoge** [qinlili23333/ReinePrint#1]
部署成功后，访问打印url出来的界面是什么样子的呢，除移动端外的其他平台是否也能正常打印呢

**Comment by qinlili23333** [comment]
![image](https://user-images.githubusercontent.com/24567775/136302010-85c00e48-58f6-41c1-8bf2-16ac0882023b.png)
qrcp接收服务
![image](https://user-images.githubusercontent.com/24567775/136302018-ade7777f-0f51-43d3-bb98-0f26ca3f5ed4.png)
filebrowser接收服务

两者均支持使用任意设备的浏览器访问
