### ISSUE TITLE
存在目录穿越漏洞

### ISSUE THREAD

**Issue by starryloki** [qinlili23333/ReinePrint#2]
qrcp上传文件时文件名中存在../时会识别成上一级目录, 可以实现任意文件写入

**Comment by qinlili23333** [comment]
测试了一下，这确实是个很严重的问题
在qrcp修复前，本项目将默认禁用qrcp，仅默认开启filebrowser接收
我将向qrcp反馈这个问题

不过这个问题有一定复现难度，需要在传输页面上通过js劫持来实现文件名的篡改，因为大多数操作系统本就不允许“/”出现在文件名中

**Comment by qinlili23333** [comment]
qrcp官方已修复漏洞，恢复启用
