### ISSUE TITLE
命令语法不正确

### ISSUE THREAD

**Issue by wzqvip** [qinlili23333/ReinePrint#3]
使用qrcp上传pdf文件，文件含空格无法打印，文件不含空格报错但是能打印

<img width="325" alt="image" src="https://github.com/qinlili23333/ReinePrint/assets/30136639/089a0d00-5b4e-4f5b-abea-f0945a875c8d">

<img width="725" alt="image" src="https://github.com/qinlili23333/ReinePrint/assets/30136639/5354bbde-14d2-499c-a5cf-414740202b47">

**Comment by qinlili23333** [comment]
已修复https://github.com/qinlili23333/ReinePrint/commit/3ff12442b429b56ef9d14223deebe09f59fe7074
